version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8000-8100:80
#       - 8080:80-90
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./www/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    
#volumes:
#  mysql_data:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
    - UPLOAD_MAX_FILESIZE=30M
    - POST_MAX_SIZE=30M

    ports:
      - 8888:80
    depends_on:
      - db

